services:
  node-backend:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "5000:5000"
    depends_on:
      - python-backend
    env_file:
      - .env

  python-backend:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5001:5001"
    env_file:
      - .env 